# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9d626361c3cd5b97d6476e17de7b3cd84b4bec7858cceeb70b7e54eb57ff0c944f02648e79ad44491603b0fba0e4a6928ca4c8f787332a2a4986ad17455d0af

test:
  secret_key_base: 022003405504112e5294a352a91a46771c0984551d4fd1a9aaf016ea7f38cd3d31012986498d5b6849c659567a0100a42406d592d34f1cc5a10d4b60a3d7aace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
